### PR TITLE
Feature add status panel

### PR DESCRIPTION
**Pull request by oscjoha**
RVIZ plugin for showing oxts status as a panel.
Is added to rviz by clicking "Panels" -> "Add New Panel" 

Selection

Run with arbitrary NCOM file or unit and output should look like this:

statuspanel

### CODE REVIEW

**Review by SebastianSvanland — APPROVED** [review]
I think it looks good. Don't know much about adding panels in Rviz but most of this looks pretty standard to the untrained eye.

**Comment by SebastianSvanland** [comment]
I just realized, it would be nice to add the information in this PR about adding the panel to a readme or something though. Otherwise the information will get lost. Or save the config file and add it to the launch options in the visualise.py launch file.

**Comment by oscjoha** [comment]
> 

Will add a README

**Comment by SebastianSvanland** [comment]
I approve (again)

**Pull request merged**
