### PR TITLE
Fix/oxts lidar

### PR DESCRIPTION
**Pull request by SebastianSvanland**
Fixed a bug when publishing lidar velocity (it would publish the lidar data on 'velocity_vehicle' instead) and cleaned up some unused code. Also added an option to disable publishing lidar and avoid warning messages for now configuring lidar specific parameters. Grouped all lidar config at the bottom of the default config file.

### CODE REVIEW

**Comment by eriadam36** [comment]
First questions before I review anything is this tested so it works theri is no difference in data output?

**Comment by SebastianSvanland** [comment]
> First questions before I review anything is this tested so it works theri is no difference in data output?

I have checked that there was no data being published on /ins/velocity_lidar at all before and now there is. I also checked that data is still published on /ins/odometry_lidar, but I haven't looked that it is correct more than that it looks like reasonable values (to the 10th power). However, I haven't touched any of the data processing so it shouldn't have changed. I only removed commented code that was never executed.

**Comment by eriadam36** [comment]
@SebastianSvanland have you had time to check the publishing messages etc to the mondeo?
I remembered that we talked about some topic and publish from oxts to mondeo.

**Comment by SebastianSvanland** [comment]
> @SebastianSvanland have you had time to check the publishing messages etc to the mondeo? I remembered that we talked about some topic and publish from oxts to mondeo.

I checked it now. We use `/oxts/fix` and `/oxts/odometry_vehicle` in our code and Dataspeed uses `/oxts/fix`, `/oxts/imu`, and `/oxts/velocity` topics. Only `/oxts/velocity` has been slightly altered (doesn't publish velocity in vehicle frame anymore, only device frame) which is already configured to take the device orientation into account. In the mondeo right now, we use a much older version of this oxts driver (oxts_ins) that doesn't even have velocity in vehicle frame so updating the driver without this fix could potentially interfere with Dataspeed's code (since we would be publishing two different frames on the same topic).

**Comment by eriadam36** [comment]
LGTM!!

**Review by eriadam36 — APPROVED** [review]

**Pull request merged**
